# Generated by Django 4.1.1 on 2022-09-19 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kinopark', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_company', models.CharField(default='', max_length=100)),
                ('publication_date', models.DateTimeField()),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kinopark.movie')),
            ],
        ),
    ]
